### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-documentation-chinese#1]
At the moment, @WynnChen is the only configured collaborator for this project. Which means that only he reviews pull requests and merges them (I do not speak Chinese and therefore do not touch the translation).

@WynnChen Do you have collaborators that should be added to this project so that they, too, can review and merge pull requests?

**Comment by WynnChen** [comment]
Unfortunately, no...

By the way, I have noticed that there are some minor format problems in the current Chinese documentation. But I am too busy with my work at the moment.  On the other hand, I also need some time to familiarize myself with the new system. I will make a complete amendment to the Chinese document later. I hope to finish these in early March.
