### ISSUE TITLE
excute "phpunit SingletonTest.php"……

### ISSUE THREAD

**Issue by muffliato1998** [sebastianbergmann/phpunit-documentation-chinese#6]
PHP Fatal error:  Uncaught Error: Undefined class constant 'PHPUnit\Runner\BaseTestRunner::STATUS_UNKNOWN' in /mnt/d/ubuntu/test.zuqe/vendor/phpunit/phpunit/src/Framework/TestBuilder.php:138
Stack trace:
#0 /mnt/d/ubuntu/test.zuqe/vendor/phpunit/phpunit/src/Framework/TestBuilder.php(117): PHPUnit\Framework\TestBuilder->buildTestWithoutData()
#1 /mnt/d/ubuntu/test.zuqe/vendor/phpunit/phpunit/src/Framework/TestSuite.php(889): PHPUnit\Framework\TestBuilder->build()
#2 /mnt/d/ubuntu/test.zuqe/vendor/phpunit/phpunit/src/Framework/TestSuite.php(231): PHPUnit\Framework\TestSuite->addTestMethod()
#3 /usr/share/php/PHPUnit/Runner/BaseTestRunner.php(106): PHPUnit\Framework\TestSuite->__construct()
#4 /usr/share/php/PHPUnit/TextUI/Command.php(169): PHPUnit\Runner\BaseTestRunner->getTest()
#5 /usr/share/php/PHPUnit/TextUI/Command.php(148): PHPUnit\TextUI\Command->run()
#6 /usr/bin/phpunit(34): PHPUnit\TextUI\Command::main()
#7 {main}
  thrown in /mnt/d/ubuntu/test.zuqe/vendor/phpunit/phpunit/src/Framework/TestBuilder.php on line 138

**Comment by WynnChen** [comment]
Not an issue related to the document.
